### ISSUE TITLE
是否可以通过判断网速大小来判断是否在监控吗

### ISSUE THREAD

**Issue by xiaoka520** [DengHanxu/SeewoMonitorSystem#1]
既然新版希沃的`media_capture.exe`会常驻，那可不可以根据这个进程的网速大小来判断是否处在监控状态呢？就不再根据这个进程是否启动来判断

**Comment by DengHanxu** [comment]
### 这是一个考虑过的理想的方法，但并未实施

当时使用的函数似乎有问题（我找了很久，很多方法，都没用），在测试时获取到的单应用网络数据始终是0。于是使用 检测程序是否在运行+总网络上传流量 的方法来间接判断。当然，这种方法存在问题与误报。不过对于学校的电脑，平时网络流量很小，看视频也是下载多。一般有大量上传出现时，叠加`media_capture.exe`运行，可以认为此时监控正在被看。我写时，`media_capture.exe`能被成功杀后台，于是就将就着用了。

你可以修改代码，加入3-5秒左右缓冲时间，对`media_capture.exe`运行但上传低的情况进行忽略。
> 对于2代，这种情况会同时亮绿灯和红灯

**Comment by xiaoka520** [comment]
今天刚因玩火绒被班主任抓，我班主任看管有点严，再加上我也不太会py，以后想办法试试
